### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Erensisman09** [andrei923/DeadByDeadlight#1]
Hello, I found a bug with sound, here is a photo
[Click](https://sun6-13.userapi.com/iBF0KhaAEoKrAxBazxpPrzS2dIMKZybe1LfoAQ/0I94F-5atPc.jpg)

**Comment by andrei923** [comment]
because you are using 1.8 sounds, you can change them in the config file.

**Comment by Erensisman09** [comment]
And where to do it??
