### ISSUE TITLE
You answered me but didn’t say which config should be changed.

### ISSUE THREAD

**Issue by Erensisman09** [andrei923/DeadByDeadlight#2]
You answered me but didn’t say which config should be changed.

**Comment by andrei923** [comment]
the sounds in config.yml.

**Comment by andrei923** [comment]
by default, it uses 1.8 sounds, in the newer minecraft versions sound names are changed so you much change them if you are not using 1.8.

**Comment by Erensisman09** [comment]
And what should be entered there? Is it necessary in **DeadByDeadlight/config.yml** or **Skript/config.sk**??

**Comment by andrei923** [comment]
DeadByDeadlight/config.yml

**Comment by Erensisman09** [comment]
Okay, in the **Sounds:** parameter, what values do you need to change? Server Version **1.12**

**Comment by andrei923** [comment]
download the new version & delete config.yml
