### ISSUE TITLE
It wont load

### ISSUE THREAD

**Issue by yambriz** [andrei923/DeadByDeadlight#3]
When i put all the stuff that dbd needed in order to run it doesn't pop up and i dont know why please help

Server Version:1.15.2

**Comment by andrei923** [comment]
send console log

**Comment by yambriz** [comment]
[latest.log](https://github.com/andrei923/DeadByDeadlight/files/4536274/latest.log)

**Comment by andrei923** [comment]
update java https://adoptopenjdk.net/

**Comment by yambriz** [comment]
which one do i chose

**Comment by yambriz** [comment]
it didn't work at first but all i had to do is restart my pc
