### ISSUE TITLE
No scoreboard and loot

### ISSUE THREAD

**Issue by yambriz** [andrei923/DeadByDeadlight#4]
So me and my friend tested the plugin but when i was hunter i had nothing and the scoreboard was not there and nothing popped up when my friend was crouching to get the generator working

**Comment by andrei923** [comment]
Send console log

**Comment by yambriz** [comment]
my bad
[latest.log](https://github.com/andrei923/DeadByDeadlight/files/4541544/latest.log)

**Comment by andrei923** [comment]
update LeafSK https://github.com/andrei923/LeafSK/releases

**Comment by yambriz** [comment]
but am using 2.1.0 and it still says that
